twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        contact_company: 'Jack Zak'
        contact_address: '123 rue du Village'
        contact_zip: '59000'
        contact_city: 'Lille'
        contact_phone: '01 23 45 67 89'
        contact_email: 'contact@jackzak.com'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths: 
        'public/img': images

when@test:
    twig:
        strict_variables: true
